version: "3"

services:
  sniffer-svc:
    build: ./sniffer_svc
#    network_mode: host
    ports:
      - "8000:8000"
    depends_on:
      - redis-sniffer-svc
      - rabbitmq
    environment:
      - REDIS_HOST=redis-sniffer-svc
      - REDIS_PORT=6379
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  system-info-svc:
    build: ./system_info_svc
#    network_mode: host
    ports:
      - "8001:8001"
    environment:
      - ENABLE_METRICS=true
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  packet-processor-svc:
    build: ./packet_processor_svc
    ports:
      - "8002:8002"
    depends_on:
      - redis-packet-processor-svc
      - rabbitmq
    environment:
      - REDIS_HOST=redis-packet-processor-svc
      - REDIS_PORT=6379
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  ml-data-processor-svc:
    build: ./ml_data_processor_svc
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
    environment:
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  ml-training-svc:
    build: ./ml_training_svc
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq
    environment:
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  threat-detection-svc:
    build: ./threat_detection_svc
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
    environment:
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro

  notification-svc:
    build: ./notification_svc
    ports:
      - "8006:8006"
    environment:
      - ENABLE_METRICS=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro
      - ./private_key.pem:/app/private_key.pem:ro

  auth-svc:
    build: ./auth_svc
    ports:
      - "8008:8008"
    environment:
      - ENABLE_METRICS=true
    volumes:
      - ./public_key.pem:/app/public_key.pem:ro
      - ./private_key.pem:/app/private_key.pem:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  redis-sniffer-svc:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  redis-packet-processor-svc:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/rabbit_conf.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana