{
 "title": "Project Hardbake Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Service API Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Total Requests by service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sniffer_svc_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_info_svc_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "packet_processor_svc_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "ml_data_processor_svc_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "ml_training_svc_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "threat_detection_svc_http_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sniffer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sniffer_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  },
  {
   "title": "System Info Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "system_info_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  },
  {
   "title": "Packet Processor Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "packet_processor_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  },
  {
   "title": "ML Data Processor Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "ml_data_processor_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  },
  {
   "title": "ML Training Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ml_training_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  },
  {
   "title": "Threat Detection Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "threat_detection_svc_http_requests_total",
     "legendFormat": "{{handler}}, {{status}}"
    }
   ]
  }
 ]
}